"""Gold regression for the de-vig arithmetic — exit criterion 2.

Unlike the Phase 1 fixture, whose values a human checks against collegefootballdata.com,
there is no external source to look a de-vigged probability up in. So the fixture is only
evidence if the human did the arithmetic *independently* and the pipeline is compared
against that. ``hand_computed`` is filled in by a person with a calculator and a Z-table;
``pipeline`` is what this project produced. The test asserts they agree.

A fixture whose ``hand_computed`` values were generated by this project's own code would
pass this test while proving nothing, which is why the generator emits them as null.
"""

from __future__ import annotations

import json
import sqlite3

import pytest

from cfb import config
from cfb.vegas.odds import moneyline_to_prob, spread_to_prob

FIXTURE_PATH = config.GOLD_DIR / "vegas_fixture.json"
TOLERANCE = 1e-4
"""Four decimal places, per the exit criterion. A human with a Z-table cannot do better."""


def load_fixture() -> dict:
    """Read the worksheet, or an empty stand-in when it has not been generated."""
    if not FIXTURE_PATH.exists():
        return {"human_verified": False, "games": []}
    return json.loads(FIXTURE_PATH.read_text())


FIXTURE = load_fixture()
GAMES = FIXTURE.get("games", [])

pytestmark = pytest.mark.skipif(
    not FIXTURE_PATH.exists(),
    reason=f"no fixture at {FIXTURE_PATH}; run scripts/make_gold_vegas_fixture.py",
)


def test_human_has_done_the_arithmetic() -> None:
    """The gate for exit criterion 2. Red until a person has worked these by hand."""
    missing = [
        f"{game['case']} ({game['game_id']}): {field}"
        for game in GAMES
        for field, value in game.get("hand_computed", {}).items()
        if value is None and (field != "p_home_moneyline" or game.get("home_moneyline") is not None)
    ]
    if missing:
        pytest.fail(
            "hand_computed values are still blank:\n  "
            + "\n  ".join(missing)
            + f"\n\nCompute them from the inputs in {FIXTURE_PATH} with a calculator and a "
            "Z-table — not by running this project's code — then fill them in."
        )
    if not FIXTURE.get("human_verified"):
        pytest.fail(
            f"{FIXTURE_PATH} has human_verified=false. Set human_verified/verified_by/"
            "verified_on once you have checked every row."
        )


def test_fixture_pins_both_signs_and_both_source_paths() -> None:
    """A fixture of five home favourites would not catch an inverted spread."""
    assert len(GAMES) >= 3, "the plan asks for 3+ hand-computed games"
    spreads = [game["spread"] for game in GAMES if game["spread"] is not None]
    assert any(spread < 0 for spread in spreads), "no home favourite in the fixture"
    assert any(spread > 0 for spread in spreads), "no away favourite in the fixture"
    assert any(game.get("home_moneyline") is not None for game in GAMES)
    assert any(game.get("home_moneyline") is None for game in GAMES)


@pytest.mark.parametrize("game", GAMES, ids=[game.get("case", "?") for game in GAMES])
class TestHandArithmeticMatchesPipeline:
    def test_p_home_devig_matches(self, game: dict) -> None:
        expected = game["hand_computed"]["p_home_devig"]
        if expected is None:
            pytest.skip("not hand-computed yet; test_human_has_done_the_arithmetic fails first")
        assert game["pipeline"]["p_home_devig"] == pytest.approx(expected, abs=TOLERANCE)

    def test_p_home_moneyline_matches(self, game: dict) -> None:
        expected = game["hand_computed"]["p_home_moneyline"]
        if expected is None:
            pytest.skip("no moneyline for this game, or not hand-computed yet")
        assert game["pipeline"]["p_home_moneyline"] == pytest.approx(expected, abs=TOLERANCE)

    def test_pipeline_values_are_reproducible_from_the_inputs(self, game: dict) -> None:
        """Recompute from the row's own inputs, so a stale fixture cannot pass quietly."""
        if game["spread"] is not None:
            assert game["pipeline"]["p_home_devig"] == pytest.approx(
                spread_to_prob(game["spread"], FIXTURE["sigma"]), abs=1e-12
            )
        if game.get("home_moneyline") is not None:
            assert game["pipeline"]["p_home_moneyline"] == pytest.approx(
                moneyline_to_prob(game["home_moneyline"], game["away_moneyline"]), abs=1e-12
            )


@pytest.mark.integration
@pytest.mark.parametrize("game", GAMES, ids=[game.get("case", "?") for game in GAMES])
def test_fixture_matches_the_built_table(built_db: sqlite3.Connection, game: dict) -> None:
    """Regression: if a later change moves the ladder or sigma, this notices."""
    exists = built_db.execute(
        "SELECT 1 FROM sqlite_master WHERE type='table' AND name='vegas_benchmark'"
    ).fetchone()
    if not exists:
        pytest.skip("vegas_benchmark not built; run `make benchmark`")

    row = built_db.execute(
        "SELECT provider, spread, home_moneyline, away_moneyline, p_home_devig, "
        "p_home_moneyline, source_type FROM vegas_benchmark WHERE game_id = ?",
        (game["game_id"],),
    ).fetchone()
    assert row is not None, f"game {game['game_id']} is missing from vegas_benchmark"

    for column in ("provider", "spread", "home_moneyline", "away_moneyline", "source_type"):
        assert row[column] == game[column], f"{column} differs for {game['game_id']}"
    assert row["p_home_devig"] == pytest.approx(game["pipeline"]["p_home_devig"], abs=1e-12)
